### ISSUE TITLE
/res link missing

### ISSUE THREAD

**Issue by arxk9** [spallas/wsd#1]
In the "Environment Setup" section, the instruction "Get the res/ data folder, complete with training and test sets, together with prebuilt dictionaries at [LINK GOOGLE DRIVE]" was given. Could you update it with the link, as you cannot run train.py without res/wsd-train/semcor+glosses_tags.txt, among others?

**Comment by spallas** [comment]
Hi,
Thanks for your interest in the project. The link is now updated: you should unzip the linked S3 resource in `res/`, you should thus obtain two directories `wsd-train` and `wed-test`.

Hope this solves your problem.

**Comment by arxk9** [comment]
Thank you!

**Comment by arxk9** [comment]
Sorry, also where is res/dictionaries/syn_lemma_vocab.txt available?

**Comment by spallas** [comment]
Yes I'm sorry. I added the link in the README also for the dictionaries folder to be added in `res/`

**Comment by arxk9** [comment]
Thank you so much! Also thanks for making this repo public; the code is very easy to use.
